version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_backendsteam
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: desweb-09-11
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
